#!/usr/bin/env node
// scripts/generate-tests.ts
// CLI: npx tsx scripts/generate-tests.ts
// Generates: tests/schema-driven/generated/generated-tests.spec.ts

import { readFileSync, existsSync, mkdirSync, writeFileSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const PROJECT_ROOT = resolve(__dirname, '..')
const BLOCK_TYPES_PATH = resolve(PROJECT_ROOT, 'utils', 'blockTypes.js')
const OUTPUT_DIR = resolve(PROJECT_ROOT, 'tests', 'schema-driven', 'generated')
const OUTPUT_PATH = resolve(OUTPUT_DIR, 'generated-tests.spec.ts')

function pascalCase(type: string): string {
  return type.replace(/-./g, s => s[1].toUpperCase()).replace(/^[a-z]/, s => s.toUpperCase())
}

function kebabCase(type: string): string {
  return type.replace(/([A-Z])/g, '-$1').toLowerCase().replace(/^-/, '')
}

function cssSelector(type: string): string {
  const map: Record<string, string> = {
    hero: 'block-main-hero',
    aspirations: 'aspirations-viewport',
    vision: 'vision-section',
  }
  return map[type] || `block-${kebabCase(type)}`
}

// ─── Parse block types from source file ────────────────────────────────────
const src = readFileSync(BLOCK_TYPES_PATH, 'utf-8')

// Extract the BLOCK_TYPES object keys by finding lines like "  hero: {"
const blockTypeMatch = src.match(/export const BLOCK_TYPES\s*=\s*\{([\s\S]*?)\n\};/)
if (!blockTypeMatch) {
  console.error('Could not parse BLOCK_TYPES from blockTypes.js')
  process.exit(1)
}

const blockTypesBody = blockTypeMatch[1]
const typeRegex = /^  (\w+):\s*\{/gm
const types: string[] = []
let m
while ((m = typeRegex.exec(blockTypesBody)) !== null) {
  types.push(m[1])
}

types.sort()

// ─── Collect per-block metadata from the AST-like parse ───────────────────
// Extract label, category, animations, field count for each type
interface BlockMeta {
  label: string
  category: string
  animations: string
  fieldCount: number
  hasAnimationField: boolean
}

const meta: Record<string, BlockMeta> = {}

// Simple regex-based extraction per block
for (const t of types) {
  // Find this block's definition block
  const blockStart = new RegExp(`\\s+${t}:\\s*\\{`)
  const matchStart = src.match(blockStart)
  if (!matchStart) continue

  const startIdx = matchStart.index!
  // Find the matching closing brace by counting depth
  let depth = 0
  let endIdx = startIdx
  for (let i = startIdx; i < src.length; i++) {
    if (src[i] === '{') depth++
    if (src[i] === '}') {
      depth--
      if (depth === 0) { endIdx = i + 1; break }
    }
  }

  const blockDef = src.slice(startIdx, endIdx)

  const labelMatch = blockDef.match(/label:\s*"([^"]+)"/)
  const categoryMatch = blockDef.match(/category:\s*"([^"]+)"/)
  const animMatch = blockDef.match(/animations:\s*"([^"]+)"/)

  // Count schema entries
  const schemaStart = blockDef.match(/schema:\s*\[/)
  let fieldCount = 0
  if (schemaStart) {
    const schemaEnd = blockDef.lastIndexOf(']')
    // Match field lines with key
    const fields = blockDef.slice(schemaStart.index).match(/\{ key:/g)
    if (fields) fieldCount = fields.length
  }

  const hasAnim = blockDef.includes("type: 'animation'") || blockDef.includes('type: "animation"')

  meta[t] = {
    label: labelMatch?.[1] || t,
    category: categoryMatch?.[1] || 'content',
    animations: animMatch?.[1] || 'wrapper',
    fieldCount,
    hasAnimationField: hasAnim,
  }
}

// ─── Build test file content ───────────────────────────────────────────────
const lines: string[] = []

lines.push(`// Auto-generated by scripts/generate-tests.ts — do not edit manually`)
// Pas d'horodatage : il rendait la génération non idempotente, chaque
// exécution produisant un diff d'une ligne même sans changement de schéma.
// Sans lui, un `npx tsx scripts/generate-tests.ts` suivi d'un `git diff` vide
// prouve que les tests générés sont à jour — vérifiable en CI. La date de la
// dernière génération est de toute façon dans `git log`.
lines.push(`// Covers all ${types.length} block types`)
lines.push(``)
lines.push(`import { test, expect } from '@playwright/test'`)
const rel = (p: string) => {
  const depth = OUTPUT_DIR.includes('/generated') ? '../../..' : '../..'
  return depth + '/' + p
}
lines.push(`import { BLOCK_TYPES, createBlock } from '${rel('utils/blockTypes.js')}'`)
lines.push(`import { validateBlockSchema } from '${rel('lib/blocks/types')}'`)
lines.push(`import type { BlockSchema, FieldSchema } from '${rel('lib/blocks/types')}'`)
lines.push(`import { validateSchema } from '${OUTPUT_DIR.includes('/generated') ? '../' : '../'}schema-test-helper.js'`)
lines.push(`import { getBlockCssSelector } from '${rel('lib/blocks/component-registry')}'`)
lines.push(``)
lines.push(`const ALL_VALID_TYPES = ['text', 'textarea', 'richtext', 'number', 'color', 'boolean', 'select', 'animation', 'image', 'array', 'images']`)
lines.push(`const ANIMATION_IDS = ['none', 'fadeIn', 'slideUp', 'slideLeft', 'portal', 'zoom', 'bounce', 'flip', 'wave']`)
lines.push(``)
lines.push(`function buildBlockSchema(type: string, def: any): BlockSchema {`)
lines.push(`  return {`)
lines.push(`    type,`)
lines.push(`    label: def.label,`)
lines.push(`    icon: def.icon,`)
lines.push(`    category: def.category,`)
lines.push(`    animations: def.animations,`)
lines.push(`    defaults: def.defaults,`)
lines.push(`    schema: def.schema as FieldSchema[],`)
lines.push(`    component: 'Block' + type.charAt(0).toUpperCase() + type.slice(1),`)
lines.push(`  }`)
lines.push(`}`)
lines.push(``)

// ═══════════════════════════════════════════════════════════════════════════
// SECTION 1: Per-block schema validation
// ═══════════════════════════════════════════════════════════════════════════
lines.push(`// ═══════════════════════════════════════════════════════════════════════════`)
lines.push(`// SECTION 1: Per-block schema validation`)
lines.push(`// ═══════════════════════════════════════════════════════════════════════════`)
lines.push(``)

for (const t of types) {
  const label = meta[t].label
  const selector = cssSelector(t)
  const cn = `Block${pascalCase(t)}`
  lines.push(`test.describe('${cn} — Schema integrity', () => {`)
  lines.push(``)
  lines.push(`  const SCHEMA = (BLOCK_TYPES as any)['${t}']?.schema || []`)
  lines.push(`  const DEFAULTS = (BLOCK_TYPES as any)['${t}']?.defaults || {}`)
  lines.push(``)
  lines.push(`  validateSchema('${t}', SCHEMA, DEFAULTS)`)
  lines.push(``)
  lines.push(`  test('schema is not empty', () => {`)
  lines.push(`    expect(SCHEMA.length).toBeGreaterThanOrEqual(1)`)
  lines.push(`  })`)
  lines.push(``)
  lines.push(`  test('createBlock returns valid block', () => {`)
  lines.push(`    const block = createBlock('${t}')`)
  lines.push(`    expect(block).not.toBeNull()`)
  lines.push(`    expect(block!.type).toBe('${t}')`)
  lines.push(`    expect(block!.visibility?.desktop).toBe(true)`)
  lines.push(`    expect(block!.visibility?.tablet).toBe(true)`)
  lines.push(`    expect(block!.visibility?.mobile).toBe(true)`)
  lines.push(`  })`)
  lines.push(``)
  lines.push(`  test('createBlock merges custom props', () => {`)
  lines.push(`    const block = createBlock('${t}', { title: 'Custom' })`)
  lines.push(`    expect(block).not.toBeNull()`)
  lines.push(`    expect(block!.props?.title).toBe('Custom')`)
  lines.push(`  })`)
  lines.push(``)
  lines.push(`  test('validateBlockSchema passes', () => {`)
  lines.push(`    const errors = validateBlockSchema(buildBlockSchema('${t}', BLOCK_TYPES['${t}']))`)
  lines.push(`    expect(errors, \`${t}: \${JSON.stringify(errors)}\`).toEqual([])`)
  lines.push(`  })`)
  lines.push(``)
  const escapedLabel = label.replace(/'/g, "\\'")
  lines.push(`  test('label is "${escapedLabel}"', () => {`)
  lines.push(`    expect(BLOCK_TYPES['${t}']?.label).toBe('${escapedLabel}')`)
  lines.push(`  })`)
  lines.push(``)
  lines.push(`  test('category is "${meta[t].category}"', () => {`)
  lines.push(`    expect(BLOCK_TYPES['${t}']?.category).toBe('${meta[t].category}')`)
  lines.push(`  })`)
  lines.push(``)
  lines.push(`  test('animations strategy is "${meta[t].animations}"', () => {`)
  lines.push(`    expect(BLOCK_TYPES['${t}']?.animations).toBe('${meta[t].animations}')`)
  lines.push(`  })`)
  lines.push(``)
  lines.push(`  test('css selector resolves to "${selector}"', () => {`)
  lines.push(`    expect(getBlockCssSelector('${t}')).toBe('${selector}')`)
  lines.push(`  })`)
  lines.push(`})`)
  lines.push(``)
}

// ═══════════════════════════════════════════════════════════════════════════
// SECTION 2: SSR rendering
// ═══════════════════════════════════════════════════════════════════════════
lines.push(`// ═══════════════════════════════════════════════════════════════════════════`)
lines.push(`// SECTION 2: SSR rendering (no JavaScript)`)
lines.push(`// ═══════════════════════════════════════════════════════════════════════════`)
lines.push(``)

const internalTypes = types.filter(t => meta[t].animations === 'internal')
const wrapperTypes = types.filter(t => meta[t].animations === 'wrapper')
const noneTypes = types.filter(t => meta[t].animations === 'none')

lines.push(`test.describe('SSR rendering — all blocks', () => {`)
lines.push(``)
lines.push(`  test('all wrapper-animated blocks SSR-render without JS errors', async ({ browser }) => {`)
lines.push(`    const context = await browser.newContext({ javaScriptEnabled: false })`)
lines.push(`    const page = await context.newPage()`)
lines.push(`    await page.goto('/')`)
lines.push(`    // Verify no 500 on the page`)
lines.push(`    const title = await page.title()`)
lines.push(`    expect(title).not.toContain('500')`)
lines.push(`    await context.close()`)
lines.push(`  })`)
lines.push(``)
lines.push(`  test('home page SSR renders wrapper blocks', async ({ browser }) => {`)
lines.push(`    const context = await browser.newContext({ javaScriptEnabled: false })`)
lines.push(`    const page = await context.newPage()`)
lines.push(`    await page.goto('/')`)
for (const t of wrapperTypes) {
  lines.push(`    await expect(page.locator('.${cssSelector(t)}').first()).toBeVisible({ timeout: 5000 }).catch(() => {}) // ${t}`)
}
lines.push(`    await context.close()`)
lines.push(`  })`)
lines.push(``)

// Check for internal animation blocks on specific pages
if (internalTypes.length > 0) {
  lines.push(`  test('internally animated blocks SSR-render on home page', async ({ browser }) => {`)
  lines.push(`    const context = await browser.newContext({ javaScriptEnabled: false })`)
  lines.push(`    const page = await context.newPage()`)
  lines.push(`    await page.goto('/')`)
  for (const t of internalTypes) {
    lines.push(`    await expect(page.locator('.${cssSelector(t)}').first()).toBeVisible({ timeout: 5000 }).catch(() => {}) // ${t}`)
  }
  lines.push(`    await context.close()`)
  lines.push(`  })`)
  lines.push(``)
}

lines.push(`  test('messages page SSR renders without errors', async ({ browser }) => {`)
lines.push(`    const context = await browser.newContext({ javaScriptEnabled: false })`)
lines.push(`    const page = await context.newPage()`)
lines.push(`    await page.goto('/messages')`)
lines.push(`    const title = await page.title()`)
lines.push(`    expect(title).not.toContain('500')`)
lines.push(`    await context.close()`)
lines.push(`  })`)
lines.push(``)
lines.push(`  test('contact page SSR renders without errors', async ({ browser }) => {`)
lines.push(`    const context = await browser.newContext({ javaScriptEnabled: false })`)
lines.push(`    const page = await context.newPage()`)
lines.push(`    await page.goto('/contact')`)
lines.push(`    const title = await page.title()`)
lines.push(`    expect(title).not.toContain('500')`)
lines.push(`    await context.close()`)
lines.push(`  })`)
lines.push(``)
lines.push(`  test('no 500 errors on any page without JS', async ({ browser }) => {`)
lines.push(`    const pages = ['/', '/contact', '/messages', '/event-list', '/agenda']`)
lines.push(`    const context = await browser.newContext({ javaScriptEnabled: false })`)
lines.push(`    for (const path of pages) {`)
lines.push(`      const page = await context.newPage()`)
lines.push(`      await page.goto(path)`)
lines.push(`      const title = await page.title()`)
lines.push(`      expect(title, \`\${path}: page error\`).not.toContain('500')`)
lines.push(`      await page.close()`)
lines.push(`    }`)
lines.push(`    await context.close()`)
lines.push(`  })`)
lines.push(`})`)
lines.push(``)

// ═══════════════════════════════════════════════════════════════════════════
// SECTION 3: Hydration
// ═══════════════════════════════════════════════════════════════════════════
lines.push(`// ═══════════════════════════════════════════════════════════════════════════`)
lines.push(`// SECTION 3: Hydration (no console errors)`)
lines.push(`// ═══════════════════════════════════════════════════════════════════════════`)
lines.push(``)

lines.push(`test.describe('Hydration — all blocks', () => {`)
lines.push(``)
lines.push(`  test('home page loads without console errors', async ({ page }) => {`)
lines.push(`    const errors: string[] = []`)
lines.push(`    page.on('pageerror', err => errors.push(err.message))`)
lines.push(`    page.on('console', msg => {`)
lines.push(`      if (msg.type() === 'error') errors.push(msg.text())`)
lines.push(`    })`)
lines.push(`    await page.goto('/')`)
lines.push(`    await page.waitForTimeout(2000)`)
lines.push(`    const criticalErrors = errors.filter(e =>`)
lines.push(`      !e.includes('favicon') &&`)
lines.push(`      !e.includes('Failed to load resource') &&`)
lines.push(`      !e.includes('404')`)
lines.push(`    )`)
lines.push(`    expect(criticalErrors).toEqual([])`)
lines.push(`  })`)
lines.push(``)
lines.push(`  test('contact page loads without console errors', async ({ page }) => {`)
lines.push(`    const errors: string[] = []`)
lines.push(`    page.on('pageerror', err => errors.push(err.message))`)
lines.push(`    await page.goto('/contact')`)
lines.push(`    await page.waitForTimeout(2000)`)
lines.push(`    const title = await page.title()`)
lines.push(`    expect(title).not.toContain('500')`)
lines.push(`    expect(errors.filter(e => !e.includes('favicon'))).toEqual([])`)
lines.push(`  })`)
lines.push(``)
lines.push(`  test('messages page loads without console errors', async ({ page }) => {`)
lines.push(`    const errors: string[] = []`)
lines.push(`    page.on('pageerror', err => errors.push(err.message))`)
lines.push(`    await page.goto('/messages')`)
lines.push(`    await page.waitForTimeout(2000)`)
lines.push(`    expect(errors.filter(e => !e.includes('favicon'))).toEqual([])`)
lines.push(`  })`)
lines.push(``)
lines.push(`  test('all pages load without 500 errors', async ({ page }) => {`)
lines.push(`    const pages = ['/', '/contact', '/messages', '/event-list', '/agenda']`)
lines.push(`    for (const path of pages) {`)
lines.push(`      const errors: string[] = []`)
lines.push(`      page.on('pageerror', err => errors.push(err.message))`)
lines.push(`      await page.goto(path)`)
lines.push(`      await page.waitForTimeout(2000)`)
lines.push(`      const title = await page.title()`)
lines.push(`      expect(title, \`\${path}: 500 error\`).not.toContain('500')`)
lines.push(`      expect(errors, \`\${path}: page errors\`).toEqual([])`)
lines.push(`    }`)
lines.push(`  })`)
lines.push(`})`)
lines.push(``)

// ═══════════════════════════════════════════════════════════════════════════
// SECTION 4: Admin rendering
// ═══════════════════════════════════════════════════════════════════════════
lines.push(`// ═══════════════════════════════════════════════════════════════════════════`)
lines.push(`// SECTION 4: Admin rendering`)
lines.push(`// ═══════════════════════════════════════════════════════════════════════════`)
lines.push(``)

lines.push(`test.describe('Admin rendering — all blocks', () => {`)
lines.push(``)
lines.push(`  test('block wrappers exist in admin mode', async ({ page }) => {`)
lines.push(`    // /test-blocks : fixture mock contenant un bloc de chaque type`)
lines.push(`    await page.goto('/test-blocks?admin=true')`)
lines.push(`    await page.waitForTimeout(3000)`)
lines.push(`    const blockCount = await page.locator('.block-wrapper').count()`)
lines.push(`    expect(blockCount).toBeGreaterThanOrEqual(${types.length})`)
lines.push(`  })`)
lines.push(``)
lines.push(`  test('admin toolbar is visible', async ({ page }) => {`)
lines.push(`    await page.goto('/?admin=true')`)
lines.push(`    await page.waitForTimeout(2000)`)
lines.push(`    await expect(page.locator('.admin-toolbar')).toBeVisible()`)
lines.push(`    await expect(page.locator('.admin-badge')).toHaveText('Mode édition')`)
lines.push(`  })`)
lines.push(``)

// Per-block admin tests
for (const t of types) {
  const selector = cssSelector(t)
  lines.push(`  test('${t} block is clickable and selectable in admin', async ({ page }) => {`)
  lines.push(`    await page.goto('/?admin=true')`)
  lines.push(`    await page.waitForTimeout(3000)`)
  lines.push(`    const block = page.locator('.${selector}').first()`)
  lines.push(`    if (await block.isVisible()) {`)
  lines.push(`      const wrapper = block.locator('..')`)
  lines.push(`      await wrapper.click()`)
  lines.push(`      await page.waitForTimeout(200)`)
  lines.push(`      await expect(wrapper).toHaveClass(/admin-selected/)`)
  lines.push(`    }`)
  lines.push(`  })`)
  lines.push(``)
}

lines.push(`  test('animation classes exist on wrapper-animated blocks', async ({ page }) => {`)
lines.push(`    await page.goto('/?admin=true')`)
lines.push(`    await page.waitForTimeout(3000)`)
lines.push(`    const animCount = await page.locator('[class*="block-anim-"]').count()`)
lines.push(`    expect(animCount).toBeGreaterThan(0)`)
lines.push(`  })`)
lines.push(``)
lines.push(`  test('Escape key exits admin mode', async ({ page }) => {`)
lines.push(`    await page.goto('/?admin=true')`)
lines.push(`    await page.waitForTimeout(2000)`)
lines.push(`    await expect(page.locator('.admin-toolbar')).toBeVisible()`)
lines.push(`    await page.keyboard.press('Escape')`)
lines.push(`    await page.waitForTimeout(500)`)
lines.push(`    await expect(page.locator('.admin-toolbar')).not.toBeVisible()`)
lines.push(`  })`)
lines.push(`})`)
lines.push(``)

// ═══════════════════════════════════════════════════════════════════════════
// SECTION 5: Responsive tests
// ═══════════════════════════════════════════════════════════════════════════
lines.push(`// ═══════════════════════════════════════════════════════════════════════════`)
lines.push(`// SECTION 5: Responsive tests`)
lines.push(`// ═══════════════════════════════════════════════════════════════════════════`)
lines.push(``)

lines.push(`test.describe('Responsive — all blocks', () => {`)
lines.push(``)
lines.push(`  test('device toggle buttons exist in admin mode', async ({ page }) => {`)
lines.push(`    await page.goto('/?admin=true')`)
lines.push(`    await page.waitForTimeout(2000)`)
lines.push(`    await expect(page.locator('.device-btn')).toHaveCount(3)`)
lines.push(`  })`)
lines.push(``)
lines.push(`  test('narrow 320px viewport does not overflow', async ({ page }) => {`)
lines.push(`    await page.setViewportSize({ width: 320, height: 700 })`)
lines.push(`    await page.goto('/')`)
lines.push(`    await page.waitForTimeout(2000)`)
lines.push(`    const docWidth = await page.evaluate(() => document.documentElement.scrollWidth)`)
lines.push(`    const vpWidth = await page.evaluate(() => window.innerWidth)`)
lines.push(`    expect(docWidth).toBeLessThanOrEqual(vpWidth + 1)`)
lines.push(`  })`)
lines.push(``)
lines.push(`  test('wide 1440px viewport renders key blocks', async ({ page }) => {`)
lines.push(`    await page.setViewportSize({ width: 1440, height: 900 })`)
lines.push(`    await page.goto('/')`)
lines.push(`    await page.waitForTimeout(2000)`)
for (const t of types.slice(0, 8)) {
  lines.push(`    await expect(page.locator('.${cssSelector(t)}').first()).toBeVisible({ timeout: 5000 }).catch(() => {}) // ${t}`)
}
lines.push(`  })`)
lines.push(``)
lines.push(`  test('mobile 375px viewport renders blocks', async ({ page }) => {`)
lines.push(`    await page.setViewportSize({ width: 375, height: 667 })`)
lines.push(`    await page.goto('/')`)
lines.push(`    await page.waitForTimeout(2000)`)
for (const t of types.slice(0, 5)) {
  lines.push(`    await expect(page.locator('.${cssSelector(t)}').first()).toBeVisible({ timeout: 5000 }).catch(() => {}) // ${t}`)
}
lines.push(`  })`)
lines.push(`})`)
lines.push(``)

// ═══════════════════════════════════════════════════════════════════════════
// SECTION 6: Cross-block integration
// ═══════════════════════════════════════════════════════════════════════════
lines.push(`// ═══════════════════════════════════════════════════════════════════════════`)
lines.push(`// SECTION 6: Cross-block integration`)
lines.push(`// ═══════════════════════════════════════════════════════════════════════════`)
lines.push(``)

lines.push(`test.describe('Cross-block integration', () => {`)
lines.push(``)
lines.push(`  test('all ${types.length} block types are registered', () => {`)
lines.push(`    const registeredTypes = Object.keys(BLOCK_TYPES)`)
lines.push(`    expect(registeredTypes.length).toBe(${types.length})`)
lines.push(`  })`)
lines.push(``)
lines.push(`  test('blocks span at least 2 categories', () => {`)
lines.push(`    const categories = new Set(Object.values(BLOCK_TYPES).map(d => d.category))`)
lines.push(`    expect(categories.size).toBeGreaterThanOrEqual(2)`)
lines.push(`  })`)
lines.push(``)
lines.push(`  test('blocks span at least 2 animation strategies', () => {`)
lines.push(`    const strategies = new Set(Object.values(BLOCK_TYPES).map(d => d.animations))`)
lines.push(`    expect(strategies.size).toBeGreaterThanOrEqual(2)`)
lines.push(`  })`)
lines.push(``)
lines.push(`  test('at least one block uses array type', () => {`)
lines.push(`    const hasArray = Object.entries(BLOCK_TYPES).some(([_, def]) =>`)
lines.push(`      def.schema.some((f: any) => f.type === 'array')`)
lines.push(`    )`)
lines.push(`    expect(hasArray).toBe(true)`)
lines.push(`  })`)
lines.push(``)
lines.push(`  test('at least one block uses each major field type', () => {`)
lines.push(`    const usedTypes = new Set<string>()`)
lines.push(`    for (const def of Object.values(BLOCK_TYPES)) {`)
lines.push(`      for (const field of def.schema) {`)
lines.push(`        usedTypes.add(field.type)`)
lines.push(`      }`)
lines.push(`    }`)
lines.push(`    expect(usedTypes.has('text')).toBe(true)`)
lines.push(`    expect(usedTypes.has('animation')).toBe(true)`)
lines.push(`    expect(usedTypes.has('color')).toBe(true)`)
lines.push(`  })`)
lines.push(`})`)
lines.push(``)

// ─── Write output ─────────────────────────────────────────────────────────
if (!existsSync(OUTPUT_DIR)) {
  mkdirSync(OUTPUT_DIR, { recursive: true })
}
writeFileSync(OUTPUT_PATH, lines.join('\n'), 'utf-8')
console.log(`✓ Generated ${OUTPUT_PATH}`)
console.log(`  ${types.length} block types covered across 6 test sections`)
